checkpoints:
  checkpoint_interval: 100000
  checkpoints_path: checkpointsz
  checkpoints_path_is_shared_file_system: false
  resume_checkpoint_path: checkpointsz
  save_initial_state: true
data:
  dataset: null
  num_loading_workers: 1
  seed: 0
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: mixtralai
  run: Mixtral-7B-v0.1
  seed: 42
  step: 0
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.025
  make_vocab_size_divisible_by: 1
  model_config:
    attn_pdrop: 0.0
    bos_token_id: 1
    eos_token_id: 2
    hidden_act: silu
    hidden_size: 1024
    initializer_range: 0.02
    intermediate_size: 3584
    is_mixtral_config: true
    max_position_embeddings: 131072
    moe_capacity_factor: 1
    moe_num_experts: 2
    num_attention_heads: 32
    num_experts_per_tok: 2
    num_hidden_layers: 1
    num_key_value_heads: 8
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_theta: 10000.0
    sliding_window_size: 4096
    tie_word_embeddings: false
    use_cache: true
    vocab_size: 32000
optimizer:
  accumulate_grad_in_fp32: false
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1.0e-08
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: null
    lr_decay_steps: 1818
    lr_decay_style: cosine
    lr_warmup_steps: 100
    lr_warmup_style: linear
    min_decay_lr: 1.0e-05
  torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 1
  expert_parallel_size: 2
  pp: 1
  pp_engine: 1f1b
  tp: 2
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: mixtralai/Mixtral-7B-v0.1
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 256
  train_steps: 1918
  val_check_interval: -1
