name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cloc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@6
      with:
        options: --exclude-dir=docs,tests,examples --exclude-lang=YAML
